name: Integration tests

on: [deployment_status]

jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    name: node v${{ matrix.node }}@${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [12, 14]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - name: Run integration tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome:headless tests"
        env:
          CI: true
          TARGET_URL: ${{ github.event.deployment_status.target_url }}
